server:
  port: 8080

spring:
  application:
    name: course
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database: mysql
    database-platform: org.hibernate .dialect.MySQLDialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  jmx:
    enabled: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/microservice?allowPublicKeyRetrieval=true&sslMode=DISABLED
    username: root
    password: root
  main:
    banner-mode: "off"
  output:
    ansi.enabled: ALWAYS